name: daily-cron-12am
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://www.supadb.dev/api/imdb?genre=mystery&start=1' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
