name: steam-weekly
on:
  workflow_dispatch:
  schedule:
    - cron: "20 0 * * 0"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      # Action genre
      - name: Action 1-45
        run: |
          curl --request GET \
          --url 'https://www.supadb.dev/api/steam?genre=Action&page=0' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
      - run: sleep 5
      - name: Action 46-90
        run: |
          curl --request GET \
          --url 'https://www.supadb.dev/api/steam?genre=Action&page=1' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'

      # Adventure genre
      - name: Adventure 1-45
        run: |
          curl --request GET \
          --url 'https://www.supadb.dev/api/steam?genre=Adventure&page=0' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
      - run: sleep 5
      - name: Adventure 46-90
        run: |
          curl --request GET \
          --url 'https://www.supadb.dev/api/steam?genre=Adventure&page=1' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
      - run: sleep 5
      # Indie genre
      - name: Indie 1-45
        run: |
          curl --request GET \
          --url 'https://www.supadb.dev/api/steam?genre=Indie&page=0' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
      - run: sleep 5
      - name: Indie 46-90
        run: |
          curl --request GET \
          --url 'https://www.supadb.dev/api/steam?genre=Indie&page=1' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
      - run: sleep 5
      # Casual genre
      - name: Casual 1-45
        run: |
          curl --request GET \
          --url 'https://www.supadb.dev/api/steam?genre=Casual&page=0' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
      - run: sleep 5
      - name: Casual 46-90
        run: |
          curl --request GET \
          --url 'https://www.supadb.dev/api/steam?genre=Casual&page=1' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
      # Sports genre
      - name: Sports 1-45
        run: |
          curl --request GET \
          --url 'https://www.supadb.dev/api/steam?genre=Sports&page=0' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
      - run: sleep 5
      - name: Sports 46-90
        run: |
          curl --request GET \
          --url 'https://www.supadb.dev/api/steam?genre=Sports&page=1' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
